title: Сайт Севелевой Л.М.
author: Севелева Людмила Михайловна
email: sevlm@tut.by
description: | # this means to ignore newlines until "baseurl:"
  Сайт Севелевой Людмилы Михайловны — педагога из Беларуси. Ордена Трудового Красного Знамени гимназия №50 г.Минска. Педагогические материалы, статьи, нормы.
# baseurl: "seveleva.com"
lang: ru # site language (en/ja/zh-Hans/zh-Hant)
author: Севелева Людмила Михайловна
tags: [Севелева Людмила Михайловна, Севелева Л М, образование, гимназия, Минск, учитель, педагог]
color_scheme: github # this specifies color scheme for syntax highlighting

# Build settings
markdown: kramdown
